model_id: "meta-llama/Meta-Llama-3.1-8B-Instruct"
dataset_path: "."
max_seq_length: 2048
output_dir: "./llama-3.1-korean-8b-hf"
report_to: "wandb"
learning_rate: 0.0002
lr_scheduler_type: "constant"
num_train_epochs: 1
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
gradient_accumulation_steps: 4
optim: "adamw_torch"
logging_steps: 10
save_strategy: "epoch"
max_grad_norm: 0.3
warmup_ratio: 0.03
bf16: true
tf32: true
gradient_checkpointing: true
fsdp: "full_shard auto_wrap"
fsdp_config:
  backward_prefetch: "backward_pre"
  forward_prefetch: "false"
  use_orig_params: "false"